### PR TITLE
Rebuild, add test & build scripts

### PR DESCRIPTION
**Pull request by jameswomack**
Hello @juliangruber! Thanks for publishing this module :star2: 

I noticed this hasn't been updated in a while, and the constants exposed by Node have changed. I've opened this PR to reflect that.

Although the build script doesn't output the constants in the same order they were in before, I manually shifted them to make the diff as easy to ready as possible.

Other than re-running the build script, I've done the following:

* Added a test (no test framework needed) to the package.json scripts block
* Added the build script to the package.json scripts block
* Updated the version number, engines and contributors block

Thanks!

### CODE REVIEW

**Comment by juliangruber** [comment]
lgtm, but can you please undo the changes to the package.json? especially the `.engines` limitation and `.version`

**Comment by jameswomack** [comment]
@juliangruber Package changes removed. I used engine as I figured you'd want the constants to match the version of Node they came from. The version number change to 1.0.0 was to ensure someone relying on the older constants wouldn't get updated to this without wanting to (e.g. ^0.0.1 will update to 0.0.2).

**Comment by juliangruber** [comment]
You could be right about the node version problem, I'd say let's keep it simple though until this is acutally reported as a problem, so we know what we're dealing with.

**Comment by juliangruber** [comment]
added you as a .contributor and released 1.0.0 :)

**Comment by jameswomack** [comment]
I appreciate being able to contribute, thank you Julian.

**Pull request merged**
